version: '3.8'

services:
  spring-api:
   build: .
   container_name: spring-api
   networks:
   - backend
   ports:
      - "8080:8080" 
   environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    SPRING_DATASOURCE_USERNAME: ${PROD_DB_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
networks:
  backend:

   